# Generated by Django 4.2.19 on 2025-02-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_post_remove_ticket_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
